FROM python:3.8-slim-buster

COPY requirements.txt /app/

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install Pillow
RUN pip install redis
RUN pip install opencv-contrib-python-headless
RUN pip install deepface

COPY . /app

CMD ["python", "/app/main.py", "-s", "1"]
